version: "3.9"

services:
  # Base de datos MySQL para el servicio 'cursos'
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sisdb2025
    ports:
      - "3307:3306" # Puerto expuesto para conexiones externas
    volumes:
      - db_data_mysql:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Base de datos PostgreSQL para el servicio 'estudiantes'
  postgres:
    image: postgres:15.3
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sisdb2025
    ports:
      - "5433:5432" # Puerto expuesto para conexiones externas
    volumes:
      - db_data_postgres:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio 'cursos'
  cursos:
    build:
      context: ./cursos/cursos
      dockerfile: Dockerfile
    container_name: cursos-container
    ports:
      - "8002:8002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/sisdb2025
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - mysql
    networks:
      - app-network

  # Servicio 'estudiantes'
  estudiantes:
    build:
      context: ./estudiantes/estudiantes
      dockerfile: Dockerfile
    container_name: estudiantes-container
    ports:
      - "8003:8003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/sisdb2025
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  db_data_mysql:
  db_data_postgres:

networks:
  app-network:
    driver: bridge
