version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sisdb2025
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  cursos:
    build:
      context: ./cursos/cursos
      dockerfile: Dockerfile
    container_name: cursos-container
    ports:
      - "8002:8002"
    environment:
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_NAME: sisdb2025
      DB_USERNAME: root
      DB_PASSWORD: admin
    depends_on:
      - mysql
    networks:
      - app-network

  estudiantes:
    build:
      context: ./estudiantes/estudiantes
      dockerfile: Dockerfile
    container_name: estudiantes-container
    ports:
      - "8003:8003"
    environment:
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_NAME: sisdb2025
      DB_USERNAME: root
      DB_PASSWORD: admin
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
